#pragma once

/* Pin definitions */
#define DISPLAY_DIG_2_PIN GPIO_NUM_12
#define DISPLAY_DIG_3_PIN GPIO_NUM_21
#define DISPLAY_DIG_4_PIN GPIO_NUM_26
#define DISPLAY_SEG_A_PIN GPIO_NUM_22
#define DISPLAY_SEG_B_PIN GPIO_NUM_23
#define DISPLAY_SEG_C_PIN GPIO_NUM_13
#define DISPLAY_SEG_D_PIN GPIO_NUM_14
#define DISPLAY_SEG_E_PIN GPIO_NUM_25
#define DISPLAY_SEG_F_PIN GPIO_NUM_19
#define DISPLAY_SEG_G_PIN GPIO_NUM_15

#define DISPLAY_SEG_A_LEDC LEDC_CHANNEL_0
#define DISPLAY_SEG_B_LEDC LEDC_CHANNEL_1
#define DISPLAY_SEG_C_LEDC LEDC_CHANNEL_2
#define DISPLAY_SEG_D_LEDC LEDC_CHANNEL_3
#define DISPLAY_SEG_E_LEDC LEDC_CHANNEL_4
#define DISPLAY_SEG_F_LEDC LEDC_CHANNEL_5
#define DISPLAY_SEG_G_LEDC LEDC_CHANNEL_6
#define DISPLAY_LEDC_MAX_DUTY 256u

#define QTOUCH_SW1_PIN GPIO_NUM_33
#define QTOUCH_SW2_PIN GPIO_NUM_27
#define QTOUCH_SW3_PIN GPIO_NUM_32

#define TEST_SPI_MISO_PIN GPIO_NUM_18
#define TEST_SPI_MOSI_PIN GPIO_NUM_5
#define TEST_SPI_SCLK_PIN GPIO_NUM_17
#define TEST_SPI_CS_PIN GPIO_NUM_16

#define I2C_SCL_PIN GPIO_NUM_0
#define I2C_SDA_PIN GPIO_NUM_4
#define I2C_PORT I2C_NUM_0


class HardwareSetup
{
public:
	static void setup();

private:
	static void setupDisplay();
	static void setupTouch();
	static void setupSPI();
};
